FROM oven/bun:1.2.2-slim AS builder

WORKDIR /app

COPY package.json tsconfig.json ./
COPY packages packages

RUN bun install --no-cache
RUN bun run build

FROM oven/bun:1.2.2-slim

WORKDIR /action

COPY --from=builder /app/dist/blinking-contrib/ ./

ENTRYPOINT ["bun", "index.js"]
