FROM oven/bun:1.2.2-slim AS builder

WORKDIR /app

COPY package.json bun.lock tsconfig.json ./
COPY packages packages

RUN bun install
RUN bun run build

FROM oven/bun:1.2.2-slim

WORKDIR /action

COPY --from=builder /app/dist/blinking-contrib/ ./

ENTRYPOINT ["bun", "index.js"]
