name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'Dockerfile'
      - 'package.json'
      - 'tsconfig.json'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        id: docker-build
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/magic-matrix:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/magic-matrix:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/magic-matrix:latest
          cache-to: type=inline

      - name: Update action.yml with new image
        run: |
          sed -i "s|image: .*|image: docker://${{ secrets.DOCKERHUB_USERNAME }}/magic-matrix@${{ steps.docker-build.outputs.digest }}|" action.yml

      - name: Commit updated action.yml
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add action.yml
          git diff --staged --quiet || git commit -m "Update Docker image digest [skip ci]"
          git push
