name: Generate Example

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build actions
        run: bun run build

      - name: Generate breathing contribution animation (light theme)
        run: bun dist/breathing-contrib/index.js
        env:
          INPUT_GITHUB_USER_NAME: ${{ github.repository_owner }}
          INPUT_OUTPUT_PATH: dist/breathing-contrib/light.svg
          INPUT_PERIOD: "6"
          INPUT_COLOR_LEVELS: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate breathing with dark theme
        run: bun dist/breathing-contrib/index.js
        env:
          INPUT_GITHUB_USER_NAME: ${{ github.repository_owner }}
          INPUT_OUTPUT_PATH: dist/breathing-contrib/dark.svg
          INPUT_PERIOD: "6"
          INPUT_COLOR_LEVELS: "#161b22,#0e4429,#006d32,#26a641,#39d353"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate blinking contribution animation
        run: bun dist/blinking-contrib/index.js
        env:
          INPUT_GITHUB_USER_NAME: ${{ github.repository_owner }}
          INPUT_OUTPUT_PATH: dist/blinking-contrib/dark.svg
          INPUT_FRAME_DURATION: "1.5"
          INPUT_TRANSITION_DURATION: "0.3"
          INPUT_COLOR_LEVELS: "#161b22,#0e4429,#006d32,#26a641,#39d353"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate blinking with light theme
        run: bun dist/blinking-contrib/index.js
        env:
          INPUT_GITHUB_USER_NAME: ${{ github.repository_owner }}
          INPUT_OUTPUT_PATH: dist/blinking-contrib/light.svg
          INPUT_FRAME_DURATION: "1.5"
          INPUT_TRANSITION_DURATION: "0.3"
          INPUT_COLOR_LEVELS: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify outputs
        run: |
          ls -la dist/
          ls -la dist/breathing-contrib/
          ls -la dist/blinking-contrib/
          test -f dist/breathing-contrib/light.svg
          test -f dist/breathing-contrib/dark.svg
          test -f dist/blinking-contrib/dark.svg
          test -f dist/blinking-contrib/light.svg
          echo "✅ All example files generated successfully"

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update output [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
