name: Generate Example

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate breathing contribution animation
        uses: ./breathing-contrib
        with:
          github_user_name: ${{ github.repository_owner }}
          output_path: dist/breathing-contrib/default.svg
          period: "2.5"
          color_levels: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"

      - name: Generate with custom colors (dark theme)
        uses: ./breathing-contrib
        with:
          github_user_name: ${{ github.repository_owner }}
          output_path: dist/breathing-contrib/dark.svg
          period: "3"
          color_levels: "#161b22,#0e4429,#006d32,#26a641,#39d353"

      - name: Generate with custom colors (ocean theme)
        uses: ./breathing-contrib
        with:
          github_user_name: ${{ github.repository_owner }}
          output_path: dist/breathing-contrib/ocean.svg
          period: "2"
          color_levels: "#ebedf0,#9fc9ff,#6eb7ff,#3d9eff,#0d7fff"

      - name: Generate blinking contribution animation
        uses: ./blinking-contrib
        with:
          github_user_name: ${{ github.repository_owner }}
          output_path: dist/blinking-contrib/default.svg
          frame_duration: "2"
          transition_duration: "0.5"
          color_levels: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"

      - name: Generate blinking with custom timing
        uses: ./blinking-contrib
        with:
          github_user_name: ${{ github.repository_owner }}
          output_path: dist/blinking-contrib/dark.svg
          frame_duration: "3"
          transition_duration: "1"
          color_levels: "#161b22,#0e4429,#006d32,#26a641,#39d353"

      - name: Verify outputs
        run: |
          ls -la dist/
          ls -la dist/breathing-contrib/
          ls -la dist/blinking-contrib/
          test -f dist/breathing-contrib/default.svg
          test -f dist/breathing-contrib/dark.svg
          test -f dist/breathing-contrib/ocean.svg
          test -f dist/blinking-contrib/default.svg
          test -f dist/blinking-contrib/dark.svg
          echo "✅ All example files generated successfully"

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update output [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
