name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version for the release (e.g., 1.0.0)"
        required: true
        type: string
      description:
        description: "Release description"
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      # Option 1: Publish to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Option 2: Publish to GitHub Container Registry (ghcr.io)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker-build
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository_owner }}/magic-matrix:${{ github.sha }}
            ${{ github.repository_owner }}/magic-matrix:${{ github.event.inputs.version }}
            ${{ github.repository_owner }}/magic-matrix:latest
            ghcr.io/${{ github.repository_owner }}/magic-matrix:${{ github.event.inputs.version }}
            ghcr.io/${{ github.repository_owner }}/magic-matrix:latest

      - name: Update action.yml with new image digest
        run: |
          sed -i "s|image: .*|image: docker://${{ github.repository_owner }}/magic-matrix@${{ steps.docker-build.outputs.digest }}|" action.yml

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build

      - name: Bump package version
        run: |
          sed -i 's/"version": ".*"/"version": "${{ github.event.inputs.version }}"/' package.json

      - name: Commit and tag release
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add action.yml package.json
          git commit -m "🚀 Release v${{ github.event.inputs.version }}"
          git tag v${{ github.event.inputs.version }}
          git push origin main --tags

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          generateReleaseNotes: true
