name: Test Published Action (Manual)

on:
  workflow_dispatch:
    inputs:
      test_user:
        description: "GitHub username to test with"
        required: false
        default: ""

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-published:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Test breathing-contrib action
      - name: Test breathing action with light theme
        uses: diverger/gh-magic-matrix/breathing-contrib@main
        with:
          github_user_name: ${{ inputs.test_user || github.repository_owner }}
          output_path: dist/test/breathing-contrib/light.svg
          period: "6"
          color_levels: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"

      - name: Test breathing with dark theme
        uses: diverger/gh-magic-matrix/breathing-contrib@main
        with:
          github_user_name: ${{ inputs.test_user || github.repository_owner }}
          output_path: dist/test/breathing-contrib/dark.svg
          period: "6"
          color_levels: "#161b22,#0e4429,#006d32,#26a641,#39d353"

      # Test blinking-contrib action
      - name: Test blinking action with light theme
        uses: diverger/gh-magic-matrix/blinking-contrib@main
        with:
          github_user_name: ${{ inputs.test_user || github.repository_owner }}
          output_path: dist/test/blinking-contrib/light.svg
          frame_duration: "3"
          transition_duration: "0.8"
          color_levels: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"

      - name: Test blinking with dark theme
        uses: diverger/gh-magic-matrix/blinking-contrib@main
        with:
          github_user_name: ${{ inputs.test_user || github.repository_owner }}
          output_path: dist/test/blinking-contrib/dark.svg
          frame_duration: "3"
          transition_duration: "0.8"
          color_levels: "#161b22,#0e4429,#006d32,#26a641,#39d353"

      # Test snake action
      - name: Test snake action with light theme
        uses: diverger/gh-magic-matrix/snake@main
        with:
          github_user_name: ${{ inputs.test_user || github.repository_owner }}
          output_path: dist/test/snake/light.svg
          snake_length: "6"
          animation_duration: "20"
          colors: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"
          show_contribution_counter: "true"
          counter_displays: |
            [
              {"position": "follow", "prefix": "🎯 ", "suffix": " contributions", "color": "#1f883d"}
            ]

      - name: Test snake with dark theme
        uses: diverger/gh-magic-matrix/snake@main
        with:
          github_user_name: ${{ inputs.test_user || github.repository_owner }}
          output_path: dist/test/snake/dark.svg
          snake_length: "6"
          animation_duration: "20"
          colors: "#161b22,#0e4429,#006d32,#26a641,#39d353"
          show_contribution_counter: "true"
          counter_displays: |
            [
              {"position": "follow", "prefix": "🎯 ", "suffix": " contributions", "color": "#7ee787"}
            ]

      - name: Verify all outputs exist
        run: |
          ls -R dist/test
          test -f dist/test/breathing-contrib/light.svg
          test -f dist/test/breathing-contrib/dark.svg
          test -f dist/test/blinking-contrib/light.svg
          test -f dist/test/blinking-contrib/dark.svg
          test -f dist/test/snake/light.svg
          test -f dist/test/snake/dark.svg
          echo "✅ All outputs generated successfully"

      - name: Publish to test-output branch
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: test-output
          build_dir: dist/test
          commit_message: "Update test output [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
